import matplotlib.pyplot as plt
import networkx as nx

# 创建有向图
G = nx.DiGraph()

# 添加节点
G.add_node("心理压力的影响")
G.add_node("飞行员情绪波动")
G.add_node("心理健康")
G.add_node("飞行效果")
G.add_node("焦虑")
G.add_node("恐慌")
G.add_node("心理压力")
G.add_node("飞行安全和效率")
G.add_node("注意力和判断力")
G.add_node("应对紧急情况的能力")
G.add_node("飞行风险")
G.add_node("身心健康问题")
G.add_node("疲劳")
G.add_node("失眠")
G.add_node("抑郁")
G.add_node("飞行员个人层面")
G.add_node("学习放松技巧")
G.add_node("情绪调节")
G.add_node("认知重构")
G.add_node("航空公司和相关机构层面")
G.add_node("重视飞行员心理健康")
G.add_node("提供支持和帮助")
G.add_node("创造良好工作环境")
G.add_node("飞行安全和效率")

# 添加边
G.add_edge("心理压力的影响", "飞行员情绪波动")
G.add_edge("飞行员情绪波动", "心理健康")
G.add_edge("心理健康", "飞行效果")
G.add_edge("心理压力的影响", "焦虑")
G.add_edge("焦虑", "心理压力")
G.add_edge("心理压力", "飞行安全和效率")
G.add_edge("心理压力的影响", "恐慌")
G.add_edge("恐慌", "心理压力")
G.add_edge("心理压力", "飞行安全和效率")
G.add_edge("心理压力的影响", "注意力和判断力")
G.add_edge("注意力和判断力", "应对紧急情况的能力")
G.add_edge("应对紧急情况的能力", "飞行风险")
G.add_edge("心理压力的影响", "身心健康问题")
G.add_edge("身心健康问题", "飞行效果")
G.add_edge("身心健康问题", "飞行员生命安全")
G.add_edge("身心健康问题", "飞行员生命安全")
G.add_edge("飞行员个人层面", "学习放松技巧")
G.add_edge("飞行员个人层面", "情绪调节")
G.add_edge("飞行员个人层面", "认知重构")
G.add_edge("航空公司和相关机构层面", "重视飞行员心理健康")
G.add_edge("航空公司和相关机构层面", "提供支持和帮助")
G.add_edge("航空公司和相关机构层面", "创造良好工作环境")
G.add_edge("航空公司和相关机构层面", "飞行安全和效率")

# 绘制流程图
pos = nx.spring_layout(G)
plt.figure(figsize=(10, 8))
nx.draw_networkx(G, pos, with_labels=True, node_size=2000, node_color='lightblue', font_size=12, font_family='WenQuanYi Micro Hei')
plt.axis('off')
plt.savefig("1.2.3.png")